version: '3.5'
services:
  lb:
    command: --docker --logLevel=DEBUG
    ports:
      - "8000:80"
      - "8080:8080"

  db:
    ports:
      - "5444:5432"

  web:
    labels:
      - "traefik.frontend.rule=PathPrefix:/"
    ports:
      - "8081:8080"
