defaultEntryPoints = ["https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
  [entryPoints.traefik]
  address = ":8080"
    # Restrict access as desired.
    # https://docs.traefik.io/configuration/entrypoints/#authentication
    # https://docs.traefik.io/configuration/entrypoints/#white-listing

[retry]
attempts = 3

[api]
dashboard = true
entryPoint = "traefik"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "example.com"
watch = true
exposedByDefault = false

[acme]
caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
email = "your_address@example.com"
storage = "/acme/certs.json"
entryPoint = "https"
onHostRule = true
  [acme.httpChallenge]
  entryPoint = "http"
