# Generated by Django 2.0.4 on 2018-04-14 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(allow_unicode=True, max_length=70, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('homepage', models.URLField(blank=True)),
            ],
            options={
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('ordinal', models.SmallIntegerField()),
                ('span', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ChapterVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateField()),
                ('length', models.IntegerField(default=0)),
                ('length_unit', models.CharField(choices=[('w', 'words'), ('c', 'chars')], default='w', max_length=1)),
                ('text', models.TextField()),
                ('text_fmt', models.CharField(choices=[('html', 'HTML'), ('md', 'Markdown'), ('rst', 'reStructuredText')], default='html', max_length=4)),
                ('authors', models.ManyToManyField(to='stories.Author')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='stories.Chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('sort_title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=70, unique=True)),
                ('added', models.DateField(blank=True, null=True)),
                ('updated', models.DateField(blank=True, null=True)),
                ('removed', models.DateField(blank=True, null=True)),
                ('slant', models.CharField(blank=True, max_length=2)),
                ('synopsis', models.TextField()),
                ('authors', models.ManyToManyField(to='stories.Author')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='stories.Library')),
            ],
            options={
                'verbose_name_plural': 'stories',
                'ordering': ('sort_title',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('abbr', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='tags',
            field=models.ManyToManyField(to='stories.Tag'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='stories.Story'),
        ),
    ]
