# Generated by Django 2.0.5 on 2018-05-08 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(allow_unicode=True, max_length=70, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('homepage', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.SmallIntegerField()),
                ('is_current', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=125)),
                ('added', models.DateField()),
                ('length', models.IntegerField(default=0)),
                ('length_unit', models.CharField(choices=[('w', 'words'), ('c', 'chars')], default='w', max_length=1)),
                ('file', models.FileField(max_length=179, upload_to='')),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('authors', models.ManyToManyField(to='stories.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('abbr', models.CharField(blank=True, max_length=15)),
                ('website', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'libraries',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('sort_title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=70, unique=True)),
                ('added', models.DateField(blank=True, null=True)),
                ('updated', models.DateField(blank=True, null=True)),
                ('removed', models.DateField(blank=True, null=True)),
                ('slant', models.CharField(blank=True, max_length=2)),
                ('synopsis', models.TextField(blank=True)),
                ('authors', models.ManyToManyField(related_name='stories', to='stories.Author')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='stories.Library')),
            ],
            options={
                'verbose_name_plural': 'stories',
                'ordering': ['sort_title'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('abbr', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['abbr'],
            },
        ),
        migrations.AddField(
            model_name='story',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='stories', to='stories.Tag'),
        ),
        migrations.AddField(
            model_name='installment',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='stories.Story'),
        ),
        migrations.AlterUniqueTogether(
            name='installment',
            unique_together={('story', 'ordinal', 'added')},
        ),
    ]
